server:
  port: 9874
spring:
  application:
    name: jr-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.79.236.88:3306/jobreview?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
     defaultZone: http://user:123456@localhost:9876/eureka/
##日志级别
logging:
  level:
    com.flamingo.jruser.dao.UserMapper: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.flamingo.jruser.model.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    #开启属性名和数据库字段名的驼峰功能
    map-underscore-to-camel-case: true
    #使全局的映射器启用或禁用缓存
    cache-enabled: true